### ISSUE TITLE
apps folder is not executable after installation

### ISSUE THREAD

**Issue by polle58** [Dica-Developer/ttws#1]
I have a working ttwatch installed on my linux mint mate 18.1.
After installing ttws I get this:
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/usr/share/ttws/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/usr/share/ttws/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:428:7)
    at startup (bootstrap_node.js:147:9)
`

**Comment by mschaaf** [comment]
Thanks for testing ttws. Do help you I need more information about your system and the commands you tried to be able to reproduce.

**Comment by polle58** [comment]
heel Martin,

Thanks for your answer,

I installed ttws on my Linuxmint 19.1 mate, the hardware is the following:

I just executed ttws  command in terminal when I got the errot I described.

If you need more information just let me know.

Thanks for your effot,


Eddy Van de Pol



eddy-thinkcentre-m92p
    description: Desktop Computer
    product: 32281Q9 (LENOVO_MT_3228)
    vendor: LENOVO
    version: ThinkCentre M92p
    serial: S4XZBX8
    width: 64 bits
    capabilities: smbios-2.7 dmi-2.7 vsyscall32
    configuration: administrator_password=disabled boot=normal chassis=desktop family=To be filled by O.E.M. keyboard_password=enabled power-on_password=disabled sku=LENOVO_MT_3228 uuid=38B06C45-971B-E311-B317-806EA50C1D00
  *-core
       description: Motherboard
       product: MAHOBAY
       vendor: LENOVO
       physical id: 0
       version: NOK
       slot: To be filled by O.E.M.
     *-firmware
          description: BIOS
          vendor: LENOVO
          physical id: 0
          version: 9SKT71AUS
          date: 07/02/2013
          size: 64KiB
          capacity: 4544KiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer acpi usb biosbootspecification uefi
     *-cache:0
          description: L2 cache
          physical id: 3e
          slot: CPU Internal L2
          size: 1MiB
          capacity: 1MiB
          capabilities: internal write-through unified
          configuration: level=2
     *-cache:1
          description: L1 cache
          physical id: 3f
          slot: CPU Internal L1
          size: 256KiB
          capacity: 256KiB
          capabilities: internal write-through data
          configuration: level=1
     *-cache:2
          description: L3 cache
          physical id: 40
          slot: CPU Internal L3
          size: 6MiB
          capacity: 6MiB
          capabilities: internal write-back unified
          configuration: level=3
     *-memory
          description: System Memory
          physical id: 41
          slot: System board or motherboard
          size: 4GiB
        *-bank:0
             description: DIMM [empty]
             product: [Empty]
             vendor: [Empty]
             physical id: 0
             serial: [Empty]
             slot: ChannelA-DIMM0
        *-bank:1
             description: DIMM DDR3 Synchronous 1600 MHz (0,6 ns)
             product: 16KTF51264AZ-1G6M1
             vendor: Micron
             physical id: 1
             serial: 29795CE0
             slot: ChannelA-DIMM1
             size: 4GiB
             width: 64 bits
             clock: 1600MHz (0.6ns)
        *-bank:2
             description: DIMM [empty]
             product: [Empty]
             vendor: [Empty]
             physical id: 2
             serial: [Empty]
             slot: ChannelB-DIMM0
        *-bank:3
             description: DIMM [empty]
             product: [Empty]
             vendor: [Empty]
             physical id: 3
             serial: [Empty]
             slot: ChannelB-DIMM1
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
          vendor: Intel Corp.
          physical id: 42
          bus info: cpu@0
          version: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
          slot: SOCKET 0
          size: 1772MHz
          capacity: 3800MHz
          width: 64 bits
          clock: 100MHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts cpufreq
          configuration: cores=4 enabledcores=4 threads=4
     *-pci
          description: Host bridge
          product: Xeon E3-1200 v2/3rd Gen Core processor DRAM Controller
          vendor: Intel Corporation
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 09
          width: 32 bits
          clock: 33MHz
          configuration: driver=ivb_uncore
          resources: irq:0
        *-pci:0
             description: PCI bridge
             product: Xeon E3-1200 v2/3rd Gen Core processor PCI Express Root Port
             vendor: Intel Corporation
             physical id: 1
             bus info: pci@0000:00:01.0
             version: 09
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:24 ioport:e000(size=4096) memory:f6000000-f70fffff ioport:e8000000(size=167772160)
           *-display
                description: VGA compatible controller
                product: NVIDIA Corporation
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
                configuration: driver=nvidia latency=0
                resources: irq:30 memory:f6000000-f6ffffff memory:e8000000-efffffff memory:f0000000-f1ffffff ioport:e000(size=128) memory:f7000000-f707ffff
           *-multimedia
                description: Audio device
                product: GK208 HDMI/DP Audio Controller
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:17 memory:f7080000-f7083fff
        *-usb:0
             description: USB controller
             product: 7 Series/C210 Series Chipset Family USB xHCI Host Controller
             vendor: Intel Corporation
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 04
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:25 memory:f7120000-f712ffff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 4.4.0-70-generic xhci-hcd
                physical id: 0
                bus info: usb@4
                logical name: usb4
                version: 4.04
                capabilities: usb-3.00
                configuration: driver=hub slots=4 speed=5000Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 4.4.0-70-generic xhci-hcd
                physical id: 1
                bus info: usb@3
                logical name: usb3
                version: 4.04
                capabilities: usb-2.00
                configuration: driver=hub slots=4 speed=480Mbit/s
              *-usb:0
                   description: Keyboard
                   product: USB NetVista Full Width Keyboard
                   vendor: CHICONY
                   physical id: 1
                   bus info: usb@3:1
                   version: 1.02
                   capabilities: usb-1.10
                   configuration: driver=usbhid maxpower=100mA speed=1Mbit/s
              *-usb:1
                   description: Mouse
                   product: USB OPTICAL MOUSE
                   vendor: Pixart Imaging, Inc.
                   physical id: 2
                   bus info: usb@3:2
                   version: 1.00
                   capabilities: usb-1.10
                   configuration: driver=usbhid maxpower=100mA speed=1Mbit/s
              *-usb:2
                   description: Printer
                   product: Officejet J5700 series
                   vendor: HP
                   physical id: 3
                   bus info: usb@3:3
                   version: 1.00
                   serial: CN87ECV3NF04TC
                   capabilities: usb-2.00 bidirectional
                   configuration: driver=usblp maxpower=2mA speed=480Mbit/s
        *-communication:0
             description: Communication controller
             product: 7 Series/C210 Series Chipset Family MEI Controller #1
             vendor: Intel Corporation
             physical id: 16
             bus info: pci@0000:00:16.0
             version: 04
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list
             configuration: driver=mei_me latency=0
             resources: irq:28 memory:f713c000-f713c00f
        *-communication:1
             description: Serial controller
             product: 7 Series/C210 Series Chipset Family KT Controller
             vendor: Intel Corporation
             physical id: 16.3
             bus info: pci@0000:00:16.3
             version: 04
             width: 32 bits
             clock: 66MHz
             capabilities: pm msi 16550 bus_master cap_list
             configuration: driver=serial latency=0
             resources: irq:19 ioport:f0a0(size=8) memory:f713a000-f713afff
        *-network
             description: Ethernet interface
             product: 82579LM Gigabit Network Connection
             vendor: Intel Corporation
             physical id: 19
             bus info: pci@0000:00:19.0
             logical name: eth0
             version: 04
             serial: fc:4d:d4:4a:94:00
             size: 1Gbit/s
             capacity: 1Gbit/s
             width: 32 bits
             clock: 33MHz
             capabilities: pm msi bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k duplex=full firmware=0.13-4 ip=192.168.0.163 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
             resources: irq:27 memory:f7100000-f711ffff memory:f7139000-f7139fff ioport:f040(size=32)
        *-usb:1
             description: USB controller
             product: 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2
             vendor: Intel Corporation
             physical id: 1a
             bus info: pci@0000:00:1a.0
             version: 04
             width: 32 bits
             clock: 33MHz
             capabilities: pm debug ehci bus_master cap_list
             configuration: driver=ehci-pci latency=0
             resources: irq:16 memory:f7138000-f71383ff
           *-usbhost
                product: EHCI Host Controller
                vendor: Linux 4.4.0-70-generic ehci_hcd
                physical id: 1
                bus info: usb@1
                logical name: usb1
                version: 4.04
                capabilities: usb-2.00
                configuration: driver=hub slots=3 speed=480Mbit/s
              *-usb
                   description: USB hub
                   product: Integrated Rate Matching Hub
                   vendor: Intel Corp.
                   physical id: 1
                   bus info: usb@1:1
                   version: 0.00
                   capabilities: usb-2.00
                   configuration: driver=hub slots=6 speed=480Mbit/s
        *-multimedia
             description: Audio device
             product: 7 Series/C210 Series Chipset Family High Definition Audio Controller
             vendor: Intel Corporation
             physical id: 1b
             bus info: pci@0000:00:1b.0
             version: 04
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress bus_master cap_list
             configuration: driver=snd_hda_intel latency=0
             resources: irq:29 memory:f7130000-f7133fff
        *-usb:2
             description: USB controller
             product: 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1
             vendor: Intel Corporation
             physical id: 1d
             bus info: pci@0000:00:1d.0
             version: 04
             width: 32 bits
             clock: 33MHz
             capabilities: pm debug ehci bus_master cap_list
             configuration: driver=ehci-pci latency=0
             resources: irq:23 memory:f7137000-f71373ff
           *-usbhost
                product: EHCI Host Controller
                vendor: Linux 4.4.0-70-generic ehci_hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 4.04
                capabilities: usb-2.00
                configuration: driver=hub slots=3 speed=480Mbit/s
              *-usb
                   description: USB hub
                   product: Integrated Rate Matching Hub
                   vendor: Intel Corp.
                   physical id: 1
                   bus info: usb@2:1
                   version: 0.00
                   capabilities: usb-2.00
                   configuration: driver=hub slots=8 speed=480Mbit/s
        *-pci:1
             description: PCI bridge
             product: 82801 PCI Bridge
             vendor: Intel Corporation
             physical id: 1e
             bus info: pci@0000:00:1e.0
             version: a4
             width: 32 bits
             clock: 33MHz
             capabilities: pci subtractive_decode bus_master cap_list
        *-isa
             description: ISA bridge
             product: Q77 Express Chipset LPC Controller
             vendor: Intel Corporation
             physical id: 1f
             bus info: pci@0000:00:1f.0
             version: 04
             width: 32 bits
             clock: 33MHz
             capabilities: isa bus_master cap_list
             configuration: driver=lpc_ich latency=0
             resources: irq:0
        *-storage
             description: SATA controller
             product: 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode]
             vendor: Intel Corporation
             physical id: 1f.2
             bus info: pci@0000:00:1f.2
             version: 04
             width: 32 bits
             clock: 66MHz
             capabilities: storage msi pm ahci_1.0 bus_master cap_list
             configuration: driver=ahci latency=0
             resources: irq:26 ioport:f090(size=8) ioport:f080(size=4) ioport:f070(size=8) ioport:f060(size=4) ioport:f020(size=32) memory:f7136000-f71367ff
        *-serial UNCLAIMED
             description: SMBus
             product: 7 Series/C210 Series Chipset Family SMBus Controller
             vendor: Intel Corporation
             physical id: 1f.3
             bus info: pci@0000:00:1f.3
             version: 04
             width: 64 bits
             clock: 33MHz
             configuration: latency=0
             resources: memory:f7135000-f71350ff ioport:f000(size=32)
     *-scsi:0
          physical id: 1
          logical name: scsi0
          capabilities: emulated
        *-disk
             description: ATA Disk
             product: Samsung SSD 850
             physical id: 0.0.0
             bus info: scsi@0:0.0.0
             logical name: /dev/sda
             version: 2B6Q
             serial: S2R6NXAH353075L
             size: 232GiB (250GB)
             capabilities: partitioned partitioned:dos
             configuration: ansiversion=5 logicalsectorsize=512 sectorsize=512 signature=0008d381
           *-volume:0
                description: EXT4 volume
                vendor: Linux
                physical id: 1
                bus info: scsi@0:0.0.0,1
                logical name: /dev/sda1
                logical name: /
                version: 1.0
                serial: b5c336e8-bc06-481d-85dd-441b421dd9da
                size: 223GiB
                capacity: 223GiB
                capabilities: primary bootable journaled extended_attributes large_files huge_files dir_nlink extents ext4 ext2 initialized
                configuration: created=2016-04-22 18:54:49 filesystem=ext4 lastmountpoint=/ modified=2017-03-29 15:43:56 mount.fstype=ext4 mount.options=rw,noatime,errors=remount-ro,data=ordered mounted=2017-03-29 10:30:07 state=mounted
           *-volume:1
                description: Linux swap volume
                physical id: 2
                bus info: scsi@0:0.0.0,2
                logical name: /dev/sda2
                version: 1
                serial: a5b8c60b-33a4-4d71-be2e-252a65562201
                size: 4768MiB
                capacity: 4768MiB
                capabilities: primary nofs swap initialized
                configuration: filesystem=swap pagesize=4096
     *-scsi:1
          physical id: 2
          logical name: scsi1
          capabilities: emulated
        *-disk
             description: ATA Disk
             product: WDC WD3200AAKS-7
             vendor: Western Digital
             physical id: 0.0.0
             bus info: scsi@1:0.0.0
             logical name: /dev/sdb
             version: 1B01
             serial: WD-WCAPZ3167406
             size: 298GiB (320GB)
             capabilities: gpt-1.00 partitioned partitioned:gpt
             configuration: ansiversion=5 guid=e93b8b24-e16e-4a80-b11a-448315de827c logicalsectorsize=512 sectorsize=512
           *-volume:0
                description: Windows FAT volume
                vendor: BSD  4.4
                physical id: 1
                bus info: scsi@1:0.0.0,1
                logical name: /dev/sdb1
                version: FAT32
                serial: 67e3-17ed
                size: 199MiB
                capacity: 199MiB
                capabilities: boot fat initialized
                configuration: FATs=2 filesystem=fat label=EFI name=EFI System Partition
           *-volume:1
                description: Apple HFS+ partition
                vendor: Mac OS X (journaled)
                physical id: 2
                bus info: scsi@1:0.0.0,2
                logical name: /dev/sdb2
                version: 4
                serial: 9b8f0139-ff53-0f97-0000-00000094f000
                size: 297GiB
                capabilities: journaled bootable osx hfsplus initialized
                configuration: boot=osx checked=2014-10-23 18:32:22 created=2014-10-23 09:32:22 filesystem=hfsplus lastmountedby=HFSJ modified=2017-03-28 17:11:39 name=Mavericks state=clean
           *-volume:2
                description: data partition
                vendor: Windows
                physical id: 3
                bus info: scsi@1:0.0.0,3
                logical name: /dev/sdb3
                serial: dd3b0803-df4c-45ab-b31c-42476b11e501
                capacity: 128MiB
     *-scsi:2
          physical id: 3
          logical name: scsi2
          capabilities: emulated
        *-cdrom
             description: DVD-RAM writer
             product: DVD-RAM SW820
             vendor: MATSHITA
             physical id: 0.0.0
             bus info: scsi@2:0.0.0
             logical name: /dev/cdrom
             logical name: /dev/cdrw
             logical name: /dev/dvd
             logical name: /dev/dvdrw
             logical name: /dev/sr0
             version: 8.41
             capabilities: removable audio cd-r cd-rw dvd dvd-r dvd-ram
             configuration: ansiversion=5 status=nodisc
  *-power UNCLAIMED
       description: To Be Filled By O.E.M.
       product: To Be Filled By O.E.M.
       vendor: To Be Filled By O.E.M.
       physical id: 1
       version: To Be Filled By O.E.M.
       serial: To Be Filled By O.E.M.
       capacity: 32768mWh


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mschaaf** [comment]
Hej @polle58 ,

thanks for your answer, but I would like to get the answer of the following questions:

1. What npm, node version are you using?
2. What are the commands you used to start ttws?
3. How did you install ttws, e.g. deb package or by cloning the repository?

**Comment by polle58** [comment]
Martin,


I tried to find out the versions you asked:



eddy@eddy-ThinkCentre-M92p ~ $ nodejs -v
v6.10.1



eddy@eddy-ThinkCentre-M92p ~ $ npm -v
3.10.10



Installed deb package on linux mint (ubuntu based)



when i try in terminal this command I get:


eddy@eddy-ThinkCentre-M92p ~ $ ttws
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/usr/share/ttws/resources/electron.asar/browser/init.js:121:9)
    at Object.<anonymous> (/usr/share/ttws/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:428:7)
    at startup (bootstrap_node.js:147:9)


Eddy


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mschaaf** [comment]
The ttws version you installed is 1.0.2?
Could you please try to clone the repo and follow the steps in the readme to run ttws from there to check if that works. Thanks.

**Comment by polle58** [comment]
Martin,


After removing the deb install and downloading the zip file and after extracting, I did this:


Start the application from the source code

1. Install [nodejs+npm](https://nodejs.org/) (I recommend to use [nvm](https://github.com/creationix/nvm) for that)
2. git clone https://github.com/Dica-Developer/ttws.git
3. cd ttws
1. npm install
2. npm start



Now ttws works, I only get an error that doesn't realy matters I think because I still didn't download activities with ttws ( see screenshot), but I have tried to renew the gpsquickfix and that seems to work



[cid:9539476c-0514-4ab9-b568-1e3d629a8e7e]










________________________________

**Comment by mschaaf** [comment]
Nice to hear that it works. There is no screenshot add your message. Could you please upload it so that I can check if it is something I have to fix. Thanks again.

**Comment by polle58** [comment]
It is in the mail I sent, maybe you can check mail instead of the message on github, if not I will look to upload it

Sent from Outlook
________________________________

**Comment by mschaaf** [comment]
It is not in the mail.

**Comment by mschaaf** [comment]
I found the reason why the deb package didn't work under mint. I will update the description and prepare a fix in the next days.

**Comment by mschaaf** [comment]
I updated the 1.0.2 release package with the fixed permission. Could you please give it a try and test that the package now works for you.
Anyways thanks for the bug report and your help in improving ttws.

**Comment by polle58** [comment]
Martin,


This release works out of the box, get the same error as I mentioned when starting from sourde but as far as I can see this is because I didn't downlad activties until now, I try to attach screenshot


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by polle58** [comment]
Martín,

Also got rid of the error message by creating a   .ttws folder in/home

Eddy

________________________________

**Comment by mschaaf** [comment]
Good to hear.
