### ISSUE TITLE
TOMTOM Runner 3 Cardio + Music

### ISSUE THREAD

**Issue by Ab3L-Baley** [Dica-Developer/ttws#2]
To access to my TOMTOM Runner 3 Cardio + Music, I had to add a new line to the file ./app/ttwatch/99-tomtom.rules:
`SUBSYSTEMS=="usb", ATTRS{idVendor}=="1390", ATTRS{idProduct}=="7476", SYMLINK+="tomtom", GROUP="usb", MODE="660"`
I'll give this information to ryanbinns/ttwatch too.

**Comment by mschaaf** [comment]
Thanks. I will update.
